// Generated by CoffeeScript 1.4.0
var assets, jsPathify;

assets = require('connect-assets');

jsPathify = require('connect-assets-jspaths');

module.exports = {
  init: function(app, done) {
    var onFileChanged;
    app.use(assets());
    onFileChanged = function(err, filePath) {};
    if (process.env.NODE_ENV === "production") {
      jsPathify(assets);
      return done(null, null);
    } else {
      return jsPathify(assets, console.log, onFileChanged, done);
    }
  }
};
