// Generated by CoffeeScript 1.4.0
var assets, config, isProd, jsPathify, topRope;

assets = require('connect-assets');

jsPathify = require('connect-assets-jspaths');

topRope = require("toprope");

config = require("./config");

isProd = process.env.NODE_ENV === "production";

module.exports = {
  init: function(app, done) {
    var onFileChanged, opts;
    opts = {
      servePath: isProd ? config.assetsRoot : ''
    };
    app.use(assets(opts));
    onFileChanged = function(err, filePath) {};
    return topRope(process.cwd() + "/public/templates", function(err, scriptTag) {
      if (err) {
        throw err;
      }
      if (isProd) {
        jsPathify(assets);
        return done(null, null);
      } else {
        console.log("Compiled Templates");
        return jsPathify(assets, console.log, onFileChanged, done);
      }
    });
  }
};
