// Generated by CoffeeScript 1.4.0
var dbUrl, devUrl, prodUrl;

prodUrl = "FILLMEIN";

devUrl = "mongodb://localhost/express-coffee";

dbUrl = process.env.NODE_ENV === "production" ? prodUrl : devUrl;

module.exports = {
  dbServer: dbUrl,
  twitter: {
    consumerKey: "",
    consumerSecret: "",
    callbackUrl: {
      dev: "",
      prod: ""
    }
  },
  facebook: {
    consumerKey: "",
    consumerSecret: "",
    callbackUrl: {
      dev: "",
      prod: ""
    }
  }
};
