// Generated by CoffeeScript 1.4.0
var dbUrl, devHost, devUrl, host, isProduction, prodHost, prodUrl;

isProduction = process.env.NODE_ENV === "production";

prodUrl = "FILLMEIN";

devUrl = "mongodb://localhost/express-coffee";

dbUrl = isProduction ? prodUrl : devUrl;

prodHost = "FILLMEIN.com";

devHost = "local.dev";

host = isProduction ? prodHost : devHost;

module.exports = {
  isProduction: isProduction,
  server: {
    host: host
  },
  assetsRoot: null,
  dbServer: dbUrl,
  twitter: {
    consumerKey: "FILLMEIN",
    consumerSecret: "FILLMEIN",
    callbackUrl: {
      dev: "",
      prod: ""
    }
  },
  facebook: {
    consumerKey: "",
    consumerSecret: "",
    callbackUrl: {
      dev: "",
      prod: ""
    }
  }
};
