// Generated by CoffeeScript 1.4.0
var app, assets, auth, connect, express, routes, stylus;

express = require('express');

stylus = require('stylus');

assets = require("./assets");

routes = require("./routes");

auth = require("./auth");

connect = require("./data").connect;

app = express();

connect();

assets.init(app, function(err, watcher) {
  var port;
  if (err) {
    throw err;
  }
  if (watcher) {
    console.log("Watching connect-assets for changes");
  }
  app.use(express["static"](process.cwd() + "/public"));
  app.set('view engine', 'jade');
  auth.init(app);
  routes.init(app);
  auth.registerRoutes(app);
  connect();
  port = process.env.PORT || process.env.VMC_APP_PORT || 3000;
  return app.listen(port, function() {
    return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
  });
});
