// Generated by CoffeeScript 1.3.3
var fs, loadFiles;

fs = require("fs");

/*
The purpose of this module is to make all our assets available without having to reference them in the view.
This is useful for requirejs, where we won't want to reference _any_ js files in the view.
*/


loadFiles = function(assetJS) {
  var loadJSDir, loadJSFile;
  loadJSFile = function(file) {
    var assetName, stat;
    stat = fs.statSync(file);
    if (stat != null ? stat.isDirectory() : void 0) {
      return loadJSDir(file);
    } else {
      assetName = (((file.replace("assets/js", "")).replace(".coffee", "")).replace(".js", "")).slice(1);
      console.log("Assetizing " + assetName);
      return assetJS(assetName);
    }
  };
  loadJSDir = function(dirPath) {
    var file, files, _i, _len;
    files = fs.readdirSync(dirPath);
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      loadJSFile("" + dirPath + "/" + file);
    }
    return true;
  };
  return loadJSFile("assets/js");
};

module.exports = {
  init: function(assetJS) {
    return loadFiles(assetJS);
  }
};
