// Generated by CoffeeScript 1.4.0
var AssetsCDN, assets, config, express, jsPaths, primeCSS, upload;

express = require('express');

assets = require("connect-assets");

jsPaths = require("connect-assets-jspaths");

AssetsCDN = require("connect-assets-cdn").AssetsCDN;

config = require("./config");

primeCSS = function(assets) {
  return assets.instance.options.helperContext.css("prod");
};

upload = function(log, done) {
  var app, bucket, cdn, key, opts, secret, _ref;
  app = express();
  opts = {
    servePath: config.assetsRoot
  };
  app.use(assets(opts));
  primeCSS(assets);
  jsPaths(assets);
  _ref = config.amazon, key = _ref.key, secret = _ref.secret, bucket = _ref.bucket;
  cdn = new AssetsCDN({
    assets: assets,
    key: key,
    secret: secret,
    bucket: bucket,
    log: log
  });
  return cdn.upload(done);
};

module.exports = {
  upload: upload
};
