// Generated by CoffeeScript 1.4.0
var api, views;

api = require("./api");

views = require("./views");

module.exports = {
  init: function(app) {
    views.init(app);
    return api.init(app);
  }
};
